import type { Marketplace } from './types';

export const STUB_MARKETPLACES: Marketplace[] = [
  {
    id: 'frontend',
    name: 'Frontend playbook',
    repoPath: 'acme/frontend-marketplace',
    remoteUrl: 'git@github.com:acme/frontend-marketplace.git',
    packageCount: 8,
    agents: ['Claude Code', 'Copilot'],
    lastPublishedRelative: '2d ago',
    state: 'healthy',
    consumers: {
      repoCount: 47,
      devCount: 32,
      outdatedRepos: 0,
      outdatedDevs: 0,
    },
  },
  {
    id: 'platform',
    name: 'Platform standards',
    repoPath: 'acme/platform-marketplace',
    remoteUrl: 'git@github.com:acme/platform-marketplace.git',
    packageCount: 14,
    agents: ['Claude Code', 'Copilot'],
    lastPublishedRelative: '6h ago',
    state: 'healthy',
    consumers: {
      repoCount: 83,
      devCount: 64,
      outdatedRepos: 0,
      outdatedDevs: 0,
    },
  },
  {
    id: 'data-platform',
    name: 'Data platform',
    repoPath: 'acme/data-marketplace',
    remoteUrl: 'git@github.com:acme/data-marketplace.git',
    packageCount: 6,
    agents: ['Claude Code'],
    lastPublishedRelative: '11d ago',
    state: 'drift',
    consumers: {
      repoCount: 19,
      devCount: 14,
      outdatedRepos: 7,
      outdatedDevs: 5,
    },
  },
  {
    id: 'mobile',
    name: 'Mobile guild',
    repoPath: 'acme/mobile-marketplace',
    remoteUrl: 'git@github.com:acme/mobile-marketplace.git',
    packageCount: 4,
    agents: ['Copilot'],
    lastPublishedRelative: '1d ago',
    state: 'healthy',
    consumers: {
      repoCount: 12,
      devCount: 9,
      outdatedRepos: 0,
      outdatedDevs: 0,
    },
  },
  {
    id: 'security',
    name: 'Security baseline',
    repoPath: 'acme/security-marketplace',
    remoteUrl: 'git@github.com:acme/security-marketplace.git',
    packageCount: 11,
    agents: ['Claude Code', 'Copilot'],
    lastPublishedRelative: '3h ago',
    state: 'healthy',
    consumers: {
      repoCount: 114,
      devCount: 86,
      outdatedRepos: 0,
      outdatedDevs: 0,
    },
  },
  {
    id: 'public-oss',
    name: 'Public OSS playbook',
    repoPath: 'acme-oss/community-marketplace',
    remoteUrl: 'git@github.com:acme-oss/community-marketplace.git',
    packageCount: 22,
    agents: ['Claude Code', 'Copilot'],
    lastPublishedRelative: '4d ago',
    state: 'healthy',
    consumers: {
      repoCount: 38,
      devCount: 142,
      outdatedRepos: 0,
      outdatedDevs: 0,
    },
  },
  {
    id: 'design-system',
    name: 'Design system rules',
    repoPath: 'acme/design-marketplace',
    remoteUrl: 'git@github.com:acme/design-marketplace.git',
    packageCount: 5,
    agents: ['Copilot'],
    lastPublishedRelative: '9d ago',
    state: 'drift',
    consumers: {
      repoCount: 22,
      devCount: 18,
      outdatedRepos: 12,
      outdatedDevs: 10,
    },
  },
];
