import { ICodingAgentDeployer } from '@packmind/coding-agent';
import { LogLevel, PackmindLogger } from '@packmind/logger';
import {
  AbstractMemberUseCase,
  MemberContext,
  PackmindEventEmitterService,
} from '@packmind/node-utils';
import {
  ArtifactsPulledEvent,
  FileUpdates,
  IAccountsPort,
  ICodingAgentPort,
  IPullContentResponse,
  IRecipesPort,
  IStandardsPort,
  OrganizationId,
  PullContentCommand,
  RecipeVersion,
  StandardVersion,
  createOrganizationId,
  createUserId,
} from '@packmind/types';
import { PackageService } from '../services/PackageService';
import { PackmindConfigService } from '../services/PackmindConfigService';
import { NoPackageSlugsProvidedError } from '../../domain/errors/NoPackageSlugsProvidedError';
import { PackagesNotFoundError } from '../../domain/errors/PackagesNotFoundError';
import { RenderModeConfigurationService } from '../services/RenderModeConfigurationService';

const origin = 'PullContentUseCase';

const TRIAL_README_CONTENT = `# Packmind playbook

This directory contains coding standards and recipes for your project, generated by [Packmind](https://github.com/PackmindHub/packmind). Follow these guidelines to ensure consistency and quality across your codebase.

## How to contribute?
1. **Create an account**: Sign up to access the playbook management features and setup instructions. Ask your agent: \`Get the activation link for my Packmind account\`
2. **Prompt to capture knowledge**: here are examples of prompts you can use to capture knowledge:
    - "Generate a Packmind Standard describing our error handling in Node.js APIs."
    - "From the last commit, create a Packmind Recipe to refactor a React component to use Hooks instead of class components."
    - "Add a rule to enforce usage of the Button component instead of plain html buttons in the standard about our design system"
3. **Distribute**: Once you've created or edited a standard or recipe, review it for accuracy and completeness, then distribute it to make it available to your team. Learn more about [distributing Packmind playbooks](https://docs.packmind.com/gs-distribute).
`;

export class PullContentUseCase extends AbstractMemberUseCase<
  PullContentCommand,
  IPullContentResponse
> {
  constructor(
    private readonly packageService: PackageService,
    private readonly recipesPort: IRecipesPort,
    private readonly standardsPort: IStandardsPort,
    private readonly codingAgentPort: ICodingAgentPort,
    private readonly renderModeConfigurationService: RenderModeConfigurationService,
    accountsPort: IAccountsPort,
    private readonly eventEmitterService: PackmindEventEmitterService,
    private readonly packmindConfigService: PackmindConfigService = new PackmindConfigService(),
    logger: PackmindLogger = new PackmindLogger(origin, LogLevel.INFO),
  ) {
    super(accountsPort, logger);
    this.logger.info('PullContentUseCase initialized');
  }

  protected async executeForMembers(
    command: PullContentCommand & MemberContext,
  ): Promise<IPullContentResponse> {
    this.logger.info('Pulling content for organization', {
      organizationId: command.organizationId,
      userId: command.userId,
      packagesSlugs: command.packagesSlugs,
    });

    // Validate that package slugs are provided (unless it's a removal-only operation)
    const isRemovalOnlyOperation =
      (!command.packagesSlugs || command.packagesSlugs.length === 0) &&
      command.previousPackagesSlugs &&
      command.previousPackagesSlugs.length > 0;

    if (
      !isRemovalOnlyOperation &&
      (!command.packagesSlugs || command.packagesSlugs.length === 0)
    ) {
      this.logger.error('Pull content failed: no package slugs provided', {
        organizationId: command.organizationId,
        userId: command.userId,
      });
      throw new NoPackageSlugsProvidedError();
    }

    try {
      // Get active coding agents for the organization
      const codingAgents =
        await this.renderModeConfigurationService.resolveActiveCodingAgents(
          command.organization.id,
        );

      this.logger.info('Using organization render modes', {
        codingAgents,
        organizationId: command.organizationId,
      });

      // Fetch packages and their artifacts (skip if removal-only operation)
      let recipeVersions: RecipeVersion[] = [];
      let standardVersions: StandardVersion[] = [];

      if (!isRemovalOnlyOperation && command.packagesSlugs) {
        const packages =
          await this.packageService.getPackagesBySlugsWithArtefacts(
            command.packagesSlugs,
            command.organization.id,
          );

        // Check if all requested slugs were found
        const foundSlugs = packages.map((pkg) => pkg.slug);
        const unknownSlugs = command.packagesSlugs.filter(
          (slug) => !foundSlugs.includes(slug),
        );

        if (unknownSlugs.length > 0) {
          this.logger.error('Pull content failed: unknown package slugs', {
            unknownSlugs,
            requestedSlugs: command.packagesSlugs,
            foundSlugs,
            organizationId: command.organizationId,
          });
          throw new PackagesNotFoundError(unknownSlugs);
        }

        this.logger.info('Found packages with relations', {
          count: packages.length,
          packagesSlugs: packages.map((p) => p.slug),
        });

        // Extract recipes and standards from packages
        const allRecipes = packages.flatMap((pkg) => pkg.recipes);
        const allStandards = packages.flatMap((pkg) => pkg.standards);

        // Deduplicate by ID (when multiple packages share the same artifact)
        const recipes = [...new Map(allRecipes.map((r) => [r.id, r])).values()];
        const standards = [
          ...new Map(allStandards.map((s) => [s.id, s])).values(),
        ];

        this.logger.info('Extracted content from packages', {
          recipeCount: recipes.length,
          standardCount: standards.length,
        });

        // Get recipe versions for recipes
        const recipeVersionsPromises = recipes.map(async (recipe) => {
          const versions = await this.recipesPort.listRecipeVersions(recipe.id);
          versions.sort(
            (a: RecipeVersion, b: RecipeVersion) => b.version - a.version,
          );
          return versions[0];
        });

        recipeVersions = (await Promise.all(recipeVersionsPromises)).filter(
          (rv): rv is NonNullable<typeof rv> => rv !== null,
        );

        this.logger.info('Retrieved recipe versions', {
          count: recipeVersions.length,
        });

        // Get standard versions for standards
        const standardVersionsPromises = standards.map(async (standard) => {
          const versions = await this.standardsPort.listStandardVersions(
            standard.id,
          );
          versions.sort((a, b) => b.version - a.version);
          return versions[0];
        });

        standardVersions = (await Promise.all(standardVersionsPromises)).filter(
          (sv) => sv !== undefined,
        );

        this.logger.info('Retrieved standard versions', {
          count: standardVersions.length,
        });
      } else {
        this.logger.info(
          'Removal-only operation: skipping package fetching, will delete all artifacts from previous packages',
        );
      }

      // Process removed packages if previousPackagesSlugs provided
      let removedRecipeVersions: RecipeVersion[] = [];
      let removedStandardVersions: StandardVersion[] = [];

      if (
        command.previousPackagesSlugs &&
        command.previousPackagesSlugs.length > 0
      ) {
        const removedPackageSlugs = this.computeRemovedPackages(
          command.previousPackagesSlugs,
          command.packagesSlugs ?? [],
        );

        if (removedPackageSlugs.length > 0) {
          this.logger.info('Detected removed packages', {
            removedPackageSlugs,
            count: removedPackageSlugs.length,
          });

          const result = await this.fetchArtifactsForRemovedPackages(
            removedPackageSlugs,
            command.organization.id,
          );
          removedRecipeVersions = result.recipeVersions;
          removedStandardVersions = result.standardVersions;

          this.logger.info('Retrieved removed artifact versions', {
            removedRecipesCount: removedRecipeVersions.length,
            removedStandardsCount: removedStandardVersions.length,
          });
        }
      }

      // Initialize the merged file updates
      const mergedFileUpdates: FileUpdates = {
        createOrUpdate: [],
        delete: [],
      };

      // Get the deployer registry
      const deployerRegistry = this.codingAgentPort.getDeployerRegistry();

      // For each coding agent, generate file updates
      for (const codingAgent of codingAgents) {
        this.logger.info('Processing coding agent', {
          codingAgent,
        });

        const deployer = deployerRegistry.getDeployer(
          codingAgent,
        ) as ICodingAgentDeployer;

        // Deploy both recipes and standards together using deployArtifacts
        // This ensures both sections are included in the same file
        const artifactFileUpdates = await deployer.deployArtifacts(
          recipeVersions,
          standardVersions,
        );

        this.logger.info('Generated artifact file updates', {
          codingAgent,
          createOrUpdateCount: artifactFileUpdates.createOrUpdate.length,
          deleteCount: artifactFileUpdates.delete.length,
        });

        this.mergeFileUpdates(mergedFileUpdates, artifactFileUpdates);

        // Generate deletion paths for removed artifacts (excluding shared ones)
        if (
          removedRecipeVersions.length > 0 ||
          removedStandardVersions.length > 0
        ) {
          const { recipeVersionsToDelete, standardVersionsToDelete } =
            this.filterSharedArtifacts(
              removedRecipeVersions,
              removedStandardVersions,
              recipeVersions,
              standardVersions,
            );

          this.logger.info('Filtered shared artifacts from deletion', {
            codingAgent,
            originalRemovedRecipes: removedRecipeVersions.length,
            actualRecipesToDelete: recipeVersionsToDelete.length,
            originalRemovedStandards: removedStandardVersions.length,
            actualStandardsToDelete: standardVersionsToDelete.length,
          });

          if (
            recipeVersionsToDelete.length > 0 ||
            standardVersionsToDelete.length > 0
          ) {
            const removalFileUpdates =
              await deployer.generateRemovalFileUpdates(
                {
                  recipeVersions: recipeVersionsToDelete,
                  standardVersions: standardVersionsToDelete,
                },
                {
                  recipeVersions: recipeVersions,
                  standardVersions: standardVersions,
                },
              );

            this.logger.info('Generated removal file updates', {
              codingAgent,
              createOrUpdateCount: removalFileUpdates.createOrUpdate.length,
              deleteCount: removalFileUpdates.delete.length,
            });

            this.mergeFileUpdates(mergedFileUpdates, removalFileUpdates);
          }
        }
      }

      // Add README.md for trial users
      const user = await this.accountsPort.getUserById(
        createUserId(command.userId),
      );
      if (user?.trial) {
        this.logger.info('Adding README.md for trial user', {
          userId: command.userId,
        });
        mergedFileUpdates.createOrUpdate.push({
          path: '.packmind/README.md',
          content: TRIAL_README_CONTENT,
        });
      }

      // Add packmind.json config file
      const configFile =
        this.packmindConfigService.createConfigFileModification(
          command.packagesSlugs,
        );
      mergedFileUpdates.createOrUpdate.push(configFile);

      this.logger.info('Successfully pulled content', {
        organizationId: command.organizationId,
        totalCreateOrUpdateCount: mergedFileUpdates.createOrUpdate.length,
        totalDeleteCount: mergedFileUpdates.delete.length,
      });

      this.eventEmitterService.emit(
        new ArtifactsPulledEvent({
          userId: createUserId(command.userId),
          organizationId: createOrganizationId(command.organizationId),
          packageSlugs: command.packagesSlugs,
          recipeCount: recipeVersions.length,
          standardCount: standardVersions.length,
          source: 'cli',
        }),
      );

      return { fileUpdates: mergedFileUpdates };
    } catch (error) {
      this.logger.error('Failed to pull content', {
        organizationId: command.organizationId,
        error: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
  }

  private mergeFileUpdates(target: FileUpdates, source: FileUpdates): void {
    // Merge createOrUpdate files (avoid duplicates by path)
    const existingPaths = new Set(target.createOrUpdate.map((f) => f.path));
    for (const file of source.createOrUpdate) {
      if (!existingPaths.has(file.path)) {
        target.createOrUpdate.push(file);
        existingPaths.add(file.path);
      }
    }

    // Merge delete files (avoid duplicates by path)
    const existingDeletePaths = new Set(target.delete.map((f) => f.path));
    for (const file of source.delete) {
      if (!existingDeletePaths.has(file.path)) {
        target.delete.push(file);
        existingDeletePaths.add(file.path);
      }
    }
  }

  /**
   * Computes which package slugs have been removed by comparing
   * previous packages with current packages
   */
  private computeRemovedPackages(
    previousSlugs: string[],
    currentSlugs: string[],
  ): string[] {
    const currentSet = new Set(currentSlugs);
    return previousSlugs.filter((slug) => !currentSet.has(slug));
  }

  /**
   * Filters removed artifacts to exclude those still needed by remaining packages.
   * Compares by recipeId/standardId since the same artifact produces the same
   * file path regardless of which package it came from.
   */
  private filterSharedArtifacts(
    removedRecipeVersions: RecipeVersion[],
    removedStandardVersions: StandardVersion[],
    remainingRecipeVersions: RecipeVersion[],
    remainingStandardVersions: StandardVersion[],
  ): {
    recipeVersionsToDelete: RecipeVersion[];
    standardVersionsToDelete: StandardVersion[];
  } {
    const remainingRecipeIds = new Set(
      remainingRecipeVersions.map((rv) => rv.recipeId),
    );
    const remainingStandardIds = new Set(
      remainingStandardVersions.map((sv) => sv.standardId),
    );

    const recipeVersionsToDelete = removedRecipeVersions.filter(
      (rv) => !remainingRecipeIds.has(rv.recipeId),
    );
    const standardVersionsToDelete = removedStandardVersions.filter(
      (sv) => !remainingStandardIds.has(sv.standardId),
    );

    return { recipeVersionsToDelete, standardVersionsToDelete };
  }

  /**
   * Fetches recipe and standard versions for the removed packages
   */
  private async fetchArtifactsForRemovedPackages(
    removedPackageSlugs: string[],
    organizationId: OrganizationId,
  ): Promise<{
    recipeVersions: RecipeVersion[];
    standardVersions: StandardVersion[];
  }> {
    // Fetch packages by slugs (they may not exist anymore, so we handle gracefully)
    const packages = await this.packageService.getPackagesBySlugsWithArtefacts(
      removedPackageSlugs,
      organizationId,
    );

    // Extract recipes and standards from removed packages
    const allRecipes = packages.flatMap((pkg) => pkg.recipes);
    const allStandards = packages.flatMap((pkg) => pkg.standards);

    // Deduplicate by ID (when multiple packages share the same artifact)
    const recipes = [...new Map(allRecipes.map((r) => [r.id, r])).values()];
    const standards = [...new Map(allStandards.map((s) => [s.id, s])).values()];

    // Get recipe versions for removed recipes
    const recipeVersionsPromises = recipes.map(async (recipe) => {
      const versions = await this.recipesPort.listRecipeVersions(recipe.id);
      versions.sort(
        (a: RecipeVersion, b: RecipeVersion) => b.version - a.version,
      );
      return versions[0];
    });

    const recipeVersions = (await Promise.all(recipeVersionsPromises)).filter(
      (rv): rv is NonNullable<typeof rv> => rv !== null,
    );

    // Get standard versions for removed standards
    const standardVersionsPromises = standards.map(async (standard) => {
      const versions = await this.standardsPort.listStandardVersions(
        standard.id,
      );
      versions.sort((a, b) => b.version - a.version);
      return versions[0];
    });

    const standardVersions = (
      await Promise.all(standardVersionsPromises)
    ).filter((sv) => sv !== undefined);

    return { recipeVersions, standardVersions };
  }
}
