import { LogLevel, PackmindLogger } from '@packmind/logger';
import {
  AbstractMemberUseCase,
  MemberContext,
  PackmindEventEmitterService,
} from '@packmind/node-utils';
import {
  ArtifactsPulledEvent,
  FileUpdates,
  CodingAgent,
  IAccountsPort,
  ICodingAgentPort,
  IPullContentResponse,
  IRecipesPort,
  ISkillsPort,
  ISpacesPort,
  IStandardsPort,
  OrganizationId,
  PackageId,
  PackageWithArtefacts,
  PullContentCommand,
  RecipeVersion,
  SkillVersion,
  SpaceId,
  StandardVersion,
  createOrganizationId,
  createUserId,
} from '@packmind/types';
import { PackageService } from '../services/PackageService';
import { PackmindConfigService } from '../services/PackmindConfigService';
import { PackmindLockFileService } from '../services/PackmindLockFileService';
import { NoPackageSlugsProvidedError } from '../../domain/errors/NoPackageSlugsProvidedError';
import { PackagesNotFoundError } from '../../domain/errors/PackagesNotFoundError';
import { RenderModeConfigurationService } from '../services/RenderModeConfigurationService';
import { IDistributionRepository } from '../../domain/repositories/IDistributionRepository';
import { TargetResolutionService } from '../services/TargetResolutionService';
import {
  buildArtifactMetadataMap,
  enrichFileModificationsWithMetadata,
  flattenArtifactMetadataMap,
} from '../utils/ArtifactMetadataUtils';

const origin = 'PullContentUseCase';

const TRIAL_README_CONTENT = `# Packmind playbook

This directory contains coding standards and recipes for your project, generated by [Packmind](https://github.com/PackmindHub/packmind). Follow these guidelines to ensure consistency and quality across your codebase.

## How to contribute?
1. **Create an account**: Sign up to access the playbook management features and setup instructions. Ask your agent: \`Get the activation link for my Packmind account\`
2. **Prompt to capture knowledge**: here are examples of prompts you can use to capture knowledge:
    - "Generate a Packmind Standard describing our error handling in Node.js APIs."
    - "From the last commit, create a Packmind Recipe to refactor a React component to use Hooks instead of class components."
    - "Add a rule to enforce usage of the Button component instead of plain html buttons in the standard about our design system"
3. **Distribute**: Once you've created or edited a standard or recipe, review it for accuracy and completeness, then distribute it to make it available to your team. Learn more about [distributing Packmind playbooks](https://docs.packmind.com/gs-distribute).
`;

export class PullContentUseCase extends AbstractMemberUseCase<
  PullContentCommand,
  IPullContentResponse
> {
  constructor(
    private readonly packageService: PackageService,
    private readonly recipesPort: IRecipesPort,
    private readonly standardsPort: IStandardsPort,
    private readonly skillsPort: ISkillsPort,
    private readonly codingAgentPort: ICodingAgentPort,
    private readonly renderModeConfigurationService: RenderModeConfigurationService,
    accountsPort: IAccountsPort,
    private readonly eventEmitterService: PackmindEventEmitterService,
    private readonly distributionRepository: IDistributionRepository,
    private readonly targetResolutionService: TargetResolutionService,
    private readonly spacesPort: ISpacesPort,
    private readonly packmindConfigService: PackmindConfigService = new PackmindConfigService(),
    private readonly lockFileService: PackmindLockFileService = new PackmindLockFileService(),
    logger: PackmindLogger = new PackmindLogger(origin, LogLevel.INFO),
  ) {
    super(accountsPort, logger);
    this.logger.info('PullContentUseCase initialized');
  }

  protected async executeForMembers(
    command: PullContentCommand & MemberContext,
  ): Promise<IPullContentResponse> {
    const { source = 'cli' } = command;

    this.logger.info('Pulling content for organization', {
      organizationId: command.organizationId,
      userId: command.userId,
      packagesSlugs: command.packagesSlugs,
    });

    // Validate that package slugs are provided (unless it's a removal-only operation)
    const isRemovalOnlyOperation =
      (!command.packagesSlugs || command.packagesSlugs.length === 0) &&
      command.previousPackagesSlugs &&
      command.previousPackagesSlugs.length > 0;

    if (
      !isRemovalOnlyOperation &&
      (!command.packagesSlugs || command.packagesSlugs.length === 0)
    ) {
      this.logger.error('Pull content failed: no package slugs provided', {
        organizationId: command.organizationId,
        userId: command.userId,
      });
      throw new NoPackageSlugsProvidedError();
    }

    try {
      let resolvedTargetId: string | undefined;

      // Get active coding agents: use command.agents if provided, otherwise fall back to org-level config
      const codingAgents =
        await this.renderModeConfigurationService.resolveCodingAgents(
          command.agents,
          command.organization.id,
        );

      // Fetch packages and their artifacts (skip if removal-only operation)
      let recipeVersions: RecipeVersion[] = [];
      let standardVersions: StandardVersion[] = [];
      let skillVersions: SkillVersion[] = [];
      let packages: PackageWithArtefacts[] = [];
      let artifactMetadata: ReturnType<typeof buildArtifactMetadataMap> | null =
        null;
      // Normalized slugs in "@space-slug/package-slug" format
      let normalizedCurrentSlugs: string[] = [];

      if (!isRemovalOnlyOperation && command.packagesSlugs) {
        const resolution = await this.resolvePackagesBySlugs(
          command.packagesSlugs,
          command.organization.id,
        );
        packages = resolution.packages;
        normalizedCurrentSlugs = resolution.normalizedSlugs;

        if (resolution.notFoundSlugs.length > 0) {
          this.logger.error('Pull content failed: unknown package slugs', {
            unknownSlugs: resolution.notFoundSlugs,
            requestedSlugs: command.packagesSlugs,
            organizationId: command.organizationId,
          });
          throw new PackagesNotFoundError(resolution.notFoundSlugs);
        }

        this.logger.info('Found packages with relations', {
          count: packages.length,
          packagesSlugs: packages.map((p) => p.slug),
        });

        // Extract recipes, standards, and skills from packages
        const allRecipes = packages.flatMap((pkg) => pkg.recipes);
        const allStandards = packages.flatMap((pkg) => pkg.standards);
        const allSkills = packages.flatMap((pkg) => pkg.skills);

        // Deduplicate by ID (when multiple packages share the same artifact)
        const recipes = [...new Map(allRecipes.map((r) => [r.id, r])).values()];
        const standards = [
          ...new Map(allStandards.map((s) => [s.id, s])).values(),
        ];
        const skills = [...new Map(allSkills.map((s) => [s.id, s])).values()];

        // Build packageIdMap per artifact type (artifact can belong to multiple packages)
        const buildPackageIdMap = (
          accessor: (pkg: PackageWithArtefacts) => { id: string }[],
        ): Map<string, string[]> => {
          const map = new Map<string, string[]>();
          for (const pkg of packages) {
            for (const artifact of accessor(pkg)) {
              const existing = map.get(artifact.id as string);
              if (existing) {
                existing.push(pkg.id as string);
              } else {
                map.set(artifact.id as string, [pkg.id as string]);
              }
            }
          }
          return map;
        };

        const recipePackageIdMap = buildPackageIdMap((pkg) => pkg.recipes);
        const standardPackageIdMap = buildPackageIdMap((pkg) => pkg.standards);
        const skillPackageIdMap = buildPackageIdMap((pkg) => pkg.skills);

        this.logger.info('Extracted content from packages', {
          recipeCount: recipes.length,
          standardCount: standards.length,
          skillCount: skills.length,
        });

        // Get recipe versions for recipes
        const recipeVersionsPromises = recipes.map(async (recipe) => {
          const versions = await this.recipesPort.listRecipeVersions(recipe.id);
          versions.sort(
            (a: RecipeVersion, b: RecipeVersion) => b.version - a.version,
          );
          return versions[0];
        });

        recipeVersions = (await Promise.all(recipeVersionsPromises)).filter(
          (rv): rv is NonNullable<typeof rv> => rv !== null,
        );

        this.logger.info('Retrieved recipe versions', {
          count: recipeVersions.length,
        });

        // Get standard versions for standards
        const standardVersionsPromises = standards.map((standard) =>
          this.standardsPort.getLatestStandardVersion(standard.id),
        );

        standardVersions = (await Promise.all(standardVersionsPromises)).filter(
          (sv) => sv !== null,
        );

        this.logger.info('Retrieved standard versions', {
          count: standardVersions.length,
        });

        // Get skill versions for skills
        const skillVersionsPromises = skills.map(async (skill) => {
          const latestVersion = await this.skillsPort.getLatestSkillVersion(
            skill.id,
          );

          // Fetch skill files for this version
          if (latestVersion) {
            const files = await this.skillsPort.getSkillFiles(latestVersion.id);
            return { ...latestVersion, files };
          }
          return null;
        });

        skillVersions = (await Promise.all(skillVersionsPromises)).filter(
          (skv) => skv !== null,
        );

        this.logger.info('Retrieved skill versions', {
          count: skillVersions.length,
        });

        // Build artifact metadata map from package artifacts and fetched versions
        artifactMetadata = buildArtifactMetadataMap({
          recipes: {
            spaceIdMap: new Map(
              recipes.map((r) => [r.id as string, r.spaceId as string]),
            ),
            packageIdMap: recipePackageIdMap,
            versions: recipeVersions,
          },
          standards: {
            spaceIdMap: new Map(
              standards.map((s) => [s.id as string, s.spaceId as string]),
            ),
            packageIdMap: standardPackageIdMap,
            versions: standardVersions,
          },
          skills: {
            spaceIdMap: new Map(
              skills.map((s) => [s.id as string, s.spaceId as string]),
            ),
            packageIdMap: skillPackageIdMap,
            versions: skillVersions,
          },
        });
      } else {
        this.logger.info(
          'Removal-only operation: skipping package fetching, will delete all artifacts from previous packages',
        );
      }

      // Process removed packages if previousPackagesSlugs provided
      let removedRecipeVersions: RecipeVersion[] = [];
      let removedStandardVersions: StandardVersion[] = [];
      let removedSkillVersions: SkillVersion[] = [];

      if (
        command.previousPackagesSlugs &&
        command.previousPackagesSlugs.length > 0
      ) {
        // Normalize previous slugs to "@space/package" format for consistent comparison
        const normalizedPreviousSlugs = await this.normalizeSlugs(
          command.previousPackagesSlugs,
          command.organization.id,
        );

        const removedPackageSlugs = this.computeRemovedPackages(
          normalizedPreviousSlugs,
          normalizedCurrentSlugs,
        );

        if (removedPackageSlugs.length > 0) {
          this.logger.info('Detected removed packages', {
            removedPackageSlugs,
            count: removedPackageSlugs.length,
          });

          const result = await this.fetchArtifactsForRemovedPackages(
            removedPackageSlugs,
            command.organization.id,
          );
          removedRecipeVersions = result.recipeVersions;
          removedStandardVersions = result.standardVersions;
          removedSkillVersions = result.skillVersions;

          this.logger.info('Retrieved removed artifact versions', {
            removedRecipesCount: removedRecipeVersions.length,
            removedStandardsCount: removedStandardVersions.length,
            removedSkillsCount: removedSkillVersions.length,
          });
        }

        // Also check for updated packages (packages that are in both lists)
        // to detect artifacts that were removed from those packages
        const updatedPackageSlugs = this.computeUpdatedPackages(
          normalizedPreviousSlugs,
          normalizedCurrentSlugs,
        );

        if (updatedPackageSlugs.length > 0) {
          this.logger.info(
            'Detected updated packages - checking for removed artifacts',
            {
              updatedPackageSlugs,
              count: updatedPackageSlugs.length,
            },
          );

          const previousResult = await this.fetchArtifactsForRemovedPackages(
            updatedPackageSlugs,
            command.organization.id,
          );

          // Add previous artifacts from updated packages to the removed lists
          // These will be filtered later by filterSharedArtifacts to exclude
          // artifacts that are still present in the current package content
          removedRecipeVersions = [
            ...removedRecipeVersions,
            ...previousResult.recipeVersions,
          ];
          removedStandardVersions = [
            ...removedStandardVersions,
            ...previousResult.standardVersions,
          ];
          removedSkillVersions = [
            ...removedSkillVersions,
            ...previousResult.skillVersions,
          ];

          this.logger.info(
            'Retrieved previous artifact versions from updated packages',
            {
              previousRecipesCount: previousResult.recipeVersions.length,
              previousStandardsCount: previousResult.standardVersions.length,
              previousSkillsCount: previousResult.skillVersions.length,
              totalRemovedRecipesCount: removedRecipeVersions.length,
              totalRemovedStandardsCount: removedStandardVersions.length,
              totalRemovedSkillsCount: removedSkillVersions.length,
            },
          );
        }
      }

      if (
        packages.length > 0 &&
        command.gitRemoteUrl &&
        command.gitBranch &&
        command.relativePath
      ) {
        const currentPackageIds = packages.map((p) => p.id) as PackageId[];

        // Query distribution history for previously deployed artifacts
        const previouslyDeployed =
          await this.targetResolutionService.findPreviouslyDeployedVersions(
            command.organization.id,
            command.userId,
            command.gitRemoteUrl,
            command.gitBranch,
            command.relativePath,
            currentPackageIds,
          );

        if (previouslyDeployed.standardVersions.length > 0) {
          this.logger.info(
            'Retrieved previously deployed standard versions from distribution history',
            { count: previouslyDeployed.standardVersions.length },
          );

          removedStandardVersions = [
            ...removedStandardVersions,
            ...previouslyDeployed.standardVersions,
          ];
        }

        if (previouslyDeployed.recipeVersions.length > 0) {
          this.logger.info(
            'Retrieved previously deployed recipe versions from distribution history',
            { count: previouslyDeployed.recipeVersions.length },
          );

          removedRecipeVersions = [
            ...removedRecipeVersions,
            ...previouslyDeployed.recipeVersions,
          ];
        }

        if (previouslyDeployed.skillVersions.length > 0) {
          this.logger.info(
            'Retrieved previously deployed skill versions from distribution history',
            { count: previouslyDeployed.skillVersions.length },
          );

          removedSkillVersions = [
            ...removedSkillVersions,
            ...previouslyDeployed.skillVersions,
          ];
        }
      }

      // Initialize the merged file updates
      const mergedFileUpdates: FileUpdates = {
        createOrUpdate: [],
        delete: [],
      };

      // Track skill versions to delete for folder cleanup
      let skillVersionsToDelete: SkillVersion[] = [];
      let removedAgents: CodingAgent[] = [];
      let cleanupSkillVersions: SkillVersion[] = [];

      // Deploy artifacts for all coding agents using the unified method
      this.logger.info('Deploying artifacts for coding agents', {
        codingAgents,
      });

      const artifactFileUpdates =
        await this.codingAgentPort.deployArtifactsForAgents({
          recipeVersions,
          standardVersions,
          skillVersions,
          codingAgents,
        });

      this.logger.info('Generated artifact file updates', {
        createOrUpdateCount: artifactFileUpdates.createOrUpdate.length,
        deleteCount: artifactFileUpdates.delete.length,
      });

      this.mergeFileUpdates(mergedFileUpdates, artifactFileUpdates);

      // Generate deletion paths for removed artifacts (excluding shared ones)
      if (
        removedRecipeVersions.length > 0 ||
        removedStandardVersions.length > 0 ||
        removedSkillVersions.length > 0
      ) {
        const filterResult = this.filterSharedArtifacts(
          removedRecipeVersions,
          removedStandardVersions,
          removedSkillVersions,
          recipeVersions,
          standardVersions,
          skillVersions,
        );
        const recipeVersionsToDelete = filterResult.recipeVersionsToDelete;
        const standardVersionsToDelete = filterResult.standardVersionsToDelete;
        skillVersionsToDelete = filterResult.skillVersionsToDelete; // Assign to outer scope

        this.logger.info('Filtered shared artifacts from deletion', {
          originalRemovedRecipes: removedRecipeVersions.length,
          actualRecipesToDelete: recipeVersionsToDelete.length,
          originalRemovedStandards: removedStandardVersions.length,
          actualStandardsToDelete: standardVersionsToDelete.length,
          originalRemovedSkills: removedSkillVersions.length,
          actualSkillsToDelete: skillVersionsToDelete.length,
        });

        if (
          recipeVersionsToDelete.length > 0 ||
          standardVersionsToDelete.length > 0 ||
          skillVersionsToDelete.length > 0
        ) {
          const removalFileUpdates =
            await this.codingAgentPort.generateRemovalUpdatesForAgents({
              removed: {
                recipeVersions: recipeVersionsToDelete,
                standardVersions: standardVersionsToDelete,
                skillVersions: skillVersionsToDelete,
              },
              installed: {
                recipeVersions,
                standardVersions,
                skillVersions,
              },
              codingAgents,
            });

          this.logger.info('Generated removal file updates', {
            createOrUpdateCount: removalFileUpdates.createOrUpdate.length,
            deleteCount: removalFileUpdates.delete.length,
          });

          this.mergeFileUpdates(mergedFileUpdates, removalFileUpdates);
        }
      }

      if (command.gitRemoteUrl && command.gitBranch && command.relativePath) {
        try {
          const target =
            await this.targetResolutionService.findOrCreateTargetFromGitInfo(
              command.organization.id,
              command.userId,
              command.gitRemoteUrl,
              command.gitBranch,
              command.relativePath,
            );

          if (target) {
            resolvedTargetId = target.id as string;

            const previousRenderModes =
              await this.distributionRepository.findActiveRenderModesByTarget(
                command.organization.id,
                target.id,
              );

            const previousAgents =
              this.renderModeConfigurationService.mapRenderModesToCodingAgents(
                previousRenderModes,
              );

            const currentAgentSet = new Set(codingAgents);
            removedAgents = previousAgents.filter(
              (agent) => !currentAgentSet.has(agent),
            );

            if (removedAgents.length > 0) {
              const [
                activeRecipeVersions,
                activeStandardVersions,
                activeSkillVersions,
              ] = await Promise.all([
                this.distributionRepository.findActiveRecipeVersionsByTarget(
                  command.organization.id,
                  target.id,
                ),
                this.distributionRepository.findActiveStandardVersionsByTarget(
                  command.organization.id,
                  target.id,
                ),
                this.distributionRepository.findActiveSkillVersionsByTarget(
                  command.organization.id,
                  target.id,
                ),
              ]);

              cleanupSkillVersions = activeSkillVersions;

              const cleanupFileUpdates =
                await this.codingAgentPort.generateAgentCleanupUpdatesForAgents(
                  {
                    agents: removedAgents,
                    artifacts: {
                      recipeVersions: activeRecipeVersions,
                      standardVersions: activeStandardVersions,
                      skillVersions: activeSkillVersions,
                    },
                  },
                );

              this.mergeFileUpdates(mergedFileUpdates, cleanupFileUpdates);
            }
          }
        } catch (error) {
          this.logger.info('Skipping agent cleanup from render mode history', {
            error: error instanceof Error ? error.message : String(error),
          });
        }
      }

      // Add README.md for trial users
      const user = await this.accountsPort.getUserById(
        createUserId(command.userId),
      );
      if (user?.trial) {
        this.logger.info('Adding README.md for trial user', {
          userId: command.userId,
        });
        mergedFileUpdates.createOrUpdate.push({
          path: '.packmind/README.md',
          content: TRIAL_README_CONTENT,
        });
      }

      // Add packmind.json config file - use normalized slugs so the config always stores "@space/package" format
      const configSlugs =
        normalizedCurrentSlugs.length > 0
          ? normalizedCurrentSlugs
          : command.packagesSlugs;
      const configFile =
        this.packmindConfigService.createConfigFileModification(
          configSlugs,
          undefined, // existingPackages - not needed, we already have all packages in packagesSlugs
          command.agents, // Pass agents to preserve them
        );
      mergedFileUpdates.createOrUpdate.push(configFile);

      // Enrich file modifications with spaceId, artifactVersion, and artifactSlug from the metadata map
      if (artifactMetadata) {
        enrichFileModificationsWithMetadata(
          mergedFileUpdates.createOrUpdate,
          artifactMetadata,
        );
      }

      // Generate packmind-lock.json
      const { artifactSpaceIds, artifactPackageIds } = artifactMetadata
        ? flattenArtifactMetadataMap(artifactMetadata)
        : { artifactSpaceIds: {}, artifactPackageIds: {} };

      const lockFile = this.lockFileService.buildLockFile({
        fileModifications: mergedFileUpdates.createOrUpdate.filter(
          (f) => f.artifactType && f.artifactId,
        ),
        recipeVersions,
        standardVersions,
        skillVersions,
        codingAgents,
        packageSlugs: command.packagesSlugs ?? [],
        targetId: resolvedTargetId,
        artifactSpaceIds,
        artifactPackageIds,
      });
      mergedFileUpdates.createOrUpdate.push(
        this.lockFileService.createLockFileModification(lockFile),
      );

      this.logger.info('Successfully pulled content', {
        organizationId: command.organizationId,
        totalCreateOrUpdateCount: mergedFileUpdates.createOrUpdate.length,
        totalDeleteCount: mergedFileUpdates.delete.length,
      });

      this.eventEmitterService.emit(
        new ArtifactsPulledEvent({
          userId: createUserId(command.userId),
          organizationId: createOrganizationId(command.organizationId),
          packageSlugs: command.packagesSlugs,
          recipeCount: recipeVersions.length,
          standardCount: standardVersions.length,
          skillCount: skillVersions.length,
          source,
        }),
      );

      // Generate skill folders for agents that support skills
      // Includes BOTH installed AND removed skills for folder cleanup
      const skillFolderPaths =
        this.codingAgentPort.getSkillsFolderPathForAgents(codingAgents);

      // Combine installed and removed skills for folder cleanup
      const allSkillsForFolderCleanup = [
        ...skillVersions,
        ...skillVersionsToDelete,
      ];

      const skillFolders = codingAgents.flatMap((agent) => {
        const skillPath = skillFolderPaths.get(agent);
        if (!skillPath) return [];
        return allSkillsForFolderCleanup.map((sv) => `${skillPath}${sv.slug}`);
      });

      const removedAgentsSkillFolders =
        removedAgents.length > 0 && cleanupSkillVersions.length > 0
          ? (() => {
              const removedSkillFolderPaths =
                this.codingAgentPort.getSkillsFolderPathForAgents(
                  removedAgents,
                );
              return removedAgents.flatMap((agent) => {
                const skillPath = removedSkillFolderPaths.get(agent);
                if (!skillPath) return [];
                return cleanupSkillVersions.map(
                  (sv) => `${skillPath}${sv.slug}`,
                );
              });
            })()
          : [];

      const mergedSkillFolders = Array.from(
        new Set([...skillFolders, ...removedAgentsSkillFolders]),
      );

      this.logger.info('Generated skill folders', {
        installedSkillCount: skillVersions.length,
        removedSkillCount: skillVersionsToDelete.length,
        totalFolderCount: mergedSkillFolders.length,
      });

      return {
        fileUpdates: mergedFileUpdates,
        skillFolders: mergedSkillFolders,
        targetId: resolvedTargetId,
        resolvedAgents: codingAgents,
      };
    } catch (error) {
      this.logger.error('Failed to pull content', {
        organizationId: command.organizationId,
        error: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
  }

  /**
   * Parses a package slug to extract optional space prefix.
   * Format: "@space-slug/package-slug" or "package-slug"
   */
  private parsePackageSlug(slug: string): {
    spaceSlug: string | null;
    packageSlug: string;
  } {
    if (slug.startsWith('@')) {
      const slashIndex = slug.indexOf('/', 1);
      if (slashIndex !== -1) {
        return {
          spaceSlug: slug.slice(1, slashIndex),
          packageSlug: slug.slice(slashIndex + 1),
        };
      }
    }
    return { spaceSlug: null, packageSlug: slug };
  }

  /**
   * Resolves packages by slugs, respecting space prefixes.
   * Slugs prefixed with "@space-slug/" are resolved within that specific space.
   * Unprefixed slugs are resolved within the organization's default space.
   * Returns packages, not-found slugs, and normalized slugs in "@space/package" format.
   */
  private async resolvePackagesBySlugs(
    slugs: string[],
    organizationId: OrganizationId,
  ): Promise<{
    packages: PackageWithArtefacts[];
    notFoundSlugs: string[];
    normalizedSlugs: string[];
  }> {
    const parsedSlugs = slugs.map((slug) => ({
      originalSlug: slug,
      ...this.parsePackageSlug(slug),
    }));

    // Group by space slug (null = default space)
    const spaceGroups = new Map<string | null, typeof parsedSlugs>();
    for (const parsed of parsedSlugs) {
      const group = spaceGroups.get(parsed.spaceSlug) ?? [];
      group.push(parsed);
      spaceGroups.set(parsed.spaceSlug, group);
    }

    // Resolve default space once if needed
    let defaultSpaceSlug: string | null = null;
    let defaultSpaceId: SpaceId | null = null;
    if (spaceGroups.has(null)) {
      const allSpaces =
        await this.spacesPort.listSpacesByOrganization(organizationId);
      const defaultSpace = allSpaces.find((s) => s.isDefaultSpace) ?? null;
      defaultSpaceId = defaultSpace?.id ?? null;
      defaultSpaceSlug = defaultSpace?.slug ?? null;
    }

    const packages: PackageWithArtefacts[] = [];
    const notFoundSlugs: string[] = [];
    // Map from originalSlug → normalizedSlug
    const normalizedSlugMap = new Map<string, string>();

    for (const [spaceSlug, group] of spaceGroups) {
      let resolvedSpaceSlug: string | null;
      let spaceId: SpaceId | null;

      if (spaceSlug === null) {
        spaceId = defaultSpaceId;
        resolvedSpaceSlug = defaultSpaceSlug;
      } else {
        const space = await this.spacesPort.getSpaceBySlug(
          spaceSlug,
          organizationId,
        );
        spaceId = space?.id ?? null;
        resolvedSpaceSlug = space?.slug ?? null;
      }

      if (!spaceId || !resolvedSpaceSlug) {
        notFoundSlugs.push(...group.map((g) => g.originalSlug));
        continue;
      }

      const pkgSlugs = group.map((g) => g.packageSlug);
      const found =
        await this.packageService.getPackagesBySlugsAndSpaceWithArtefacts(
          pkgSlugs,
          spaceId,
        );
      packages.push(...found);

      const foundSlugs = new Set(found.map((p) => p.slug));
      for (const g of group) {
        if (!foundSlugs.has(g.packageSlug)) {
          notFoundSlugs.push(g.originalSlug);
        } else {
          normalizedSlugMap.set(
            g.originalSlug,
            `@${resolvedSpaceSlug}/${g.packageSlug}`,
          );
        }
      }
    }

    const normalizedSlugs = slugs
      .map((slug) => normalizedSlugMap.get(slug))
      .filter((s): s is string => s !== undefined);

    return { packages, notFoundSlugs, normalizedSlugs };
  }

  /**
   * Normalizes package slugs to "@space-slug/package-slug" format.
   * Unprefixed slugs are resolved to the organization's default space.
   * Already-prefixed slugs are returned as-is.
   */
  private async normalizeSlugs(
    slugs: string[],
    organizationId: OrganizationId,
  ): Promise<string[]> {
    const hasUnprefixed = slugs.some((s) => !s.startsWith('@'));
    let defaultSpaceSlug: string | null = null;
    if (hasUnprefixed) {
      const allSpaces =
        await this.spacesPort.listSpacesByOrganization(organizationId);
      defaultSpaceSlug = allSpaces.find((s) => s.isDefaultSpace)?.slug ?? null;
    }

    return slugs.map((slug) => {
      if (slug.startsWith('@')) return slug;
      if (defaultSpaceSlug) return `@${defaultSpaceSlug}/${slug}`;
      return slug;
    });
  }

  private mergeFileUpdates(target: FileUpdates, source: FileUpdates): void {
    // Merge createOrUpdate files (avoid duplicates by path)
    const existingPaths = new Set(target.createOrUpdate.map((f) => f.path));
    for (const file of source.createOrUpdate) {
      if (!existingPaths.has(file.path)) {
        target.createOrUpdate.push(file);
        existingPaths.add(file.path);
      }
    }

    // Merge delete files (avoid duplicates by path)
    const existingDeletePaths = new Set(target.delete.map((f) => f.path));
    for (const file of source.delete) {
      if (!existingDeletePaths.has(file.path)) {
        target.delete.push(file);
        existingDeletePaths.add(file.path);
      }
    }
  }

  /**
   * Computes which package slugs have been removed by comparing
   * previous packages with current packages
   */
  private computeRemovedPackages(
    previousSlugs: string[],
    currentSlugs: string[],
  ): string[] {
    const currentSet = new Set(currentSlugs);
    return previousSlugs.filter((slug) => !currentSet.has(slug));
  }

  /**
   * Computes packages that are in both previous and current lists (updated packages).
   * These packages may have had artifacts added or removed.
   */
  private computeUpdatedPackages(
    previousSlugs: string[],
    currentSlugs: string[],
  ): string[] {
    const currentSet = new Set(currentSlugs);
    return previousSlugs.filter((slug) => currentSet.has(slug));
  }

  /**
   * Filters removed artifacts to exclude those still needed by remaining packages.
   * Compares by recipeId/standardId/skillId since the same artifact produces the same
   * file path regardless of which package it came from.
   */
  private filterSharedArtifacts(
    removedRecipeVersions: RecipeVersion[],
    removedStandardVersions: StandardVersion[],
    removedSkillVersions: SkillVersion[],
    remainingRecipeVersions: RecipeVersion[],
    remainingStandardVersions: StandardVersion[],
    remainingSkillVersions: SkillVersion[],
  ): {
    recipeVersionsToDelete: RecipeVersion[];
    standardVersionsToDelete: StandardVersion[];
    skillVersionsToDelete: SkillVersion[];
  } {
    const remainingRecipeIds = new Set(
      remainingRecipeVersions.map((rv) => rv.recipeId),
    );
    const remainingStandardIds = new Set(
      remainingStandardVersions.map((sv) => sv.standardId),
    );
    const remainingSkillIds = new Set(
      remainingSkillVersions.map((skv) => skv.skillId),
    );

    const recipeVersionsToDelete = removedRecipeVersions.filter(
      (rv) => !remainingRecipeIds.has(rv.recipeId),
    );
    const standardVersionsToDelete = removedStandardVersions.filter(
      (sv) => !remainingStandardIds.has(sv.standardId),
    );
    const skillVersionsToDelete = removedSkillVersions.filter(
      (skv) => !remainingSkillIds.has(skv.skillId),
    );

    return {
      recipeVersionsToDelete,
      standardVersionsToDelete,
      skillVersionsToDelete,
    };
  }

  /**
   * Fetches recipe, standard, and skill versions for the removed packages
   */
  private async fetchArtifactsForRemovedPackages(
    removedPackageSlugs: string[],
    organizationId: OrganizationId,
  ): Promise<{
    recipeVersions: RecipeVersion[];
    standardVersions: StandardVersion[];
    skillVersions: SkillVersion[];
  }> {
    // Fetch packages by slugs (they may not exist anymore, so we handle gracefully)
    const { packages } = await this.resolvePackagesBySlugs(
      removedPackageSlugs,
      organizationId,
    );

    // Extract recipes, standards, and skills from removed packages
    const allRecipes = packages.flatMap((pkg) => pkg.recipes);
    const allStandards = packages.flatMap((pkg) => pkg.standards);
    const allSkills = packages.flatMap((pkg) => pkg.skills);

    // Deduplicate by ID (when multiple packages share the same artifact)
    const recipes = [...new Map(allRecipes.map((r) => [r.id, r])).values()];
    const standards = [...new Map(allStandards.map((s) => [s.id, s])).values()];
    const skills = [...new Map(allSkills.map((s) => [s.id, s])).values()];

    // Get recipe versions for removed recipes
    const recipeVersionsPromises = recipes.map(async (recipe) => {
      const versions = await this.recipesPort.listRecipeVersions(recipe.id);
      versions.sort(
        (a: RecipeVersion, b: RecipeVersion) => b.version - a.version,
      );
      return versions[0];
    });

    const recipeVersions = (await Promise.all(recipeVersionsPromises)).filter(
      (rv): rv is NonNullable<typeof rv> => rv !== null,
    );

    // Get standard versions for removed standards
    const standardVersionsPromises = standards.map((standard) =>
      this.standardsPort.getLatestStandardVersion(standard.id),
    );

    const standardVersions = (
      await Promise.all(standardVersionsPromises)
    ).filter((sv) => sv !== null);

    // Get skill versions for removed skills
    const skillVersionsPromises = skills.map((skill) =>
      this.skillsPort.getLatestSkillVersion(skill.id),
    );

    const skillVersions = (await Promise.all(skillVersionsPromises)).filter(
      (skv) => skv !== null,
    );

    return { recipeVersions, standardVersions, skillVersions };
  }
}
