services:
  postgres:
    image: postgres:17-alpine
    container_name: packmind-prod-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: packmind
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  install-dependencies:
    image: node:24.18.0-alpine3.23
    container_name: packmind-prod-install-deps
    volumes:
      - .:/packmind
    working_dir: /packmind
    entrypoint: npm install

volumes:
  postgres-data-prod:
