import * as fs from 'fs/promises';
import * as path from 'path';
import { IOnboardingDraft } from '../../domain/types/OnboardingDraft';

export type DraftFormat = 'json' | 'md' | 'both';

export interface IDraftWriteResult {
  jsonPath: string | null;
  mdPath: string | null;
}

export class DraftFileWriterService {
  private readonly JSON_FILENAME = 'packmind-onboard.draft.json';
  private readonly MD_FILENAME = 'packmind-onboard.draft.md';

  async writeDraftFiles(
    draft: IOnboardingDraft,
    outputDir: string,
    format: DraftFormat = 'both',
  ): Promise<IDraftWriteResult> {
    await fs.mkdir(outputDir, { recursive: true });

    const result: IDraftWriteResult = {
      jsonPath: null,
      mdPath: null,
    };

    if (format === 'json' || format === 'both') {
      const jsonPath = path.join(outputDir, this.JSON_FILENAME);
      await fs.writeFile(jsonPath, JSON.stringify(draft, null, 2), 'utf-8');
      result.jsonPath = jsonPath;
    }

    if (format === 'md' || format === 'both') {
      const mdPath = path.join(outputDir, this.MD_FILENAME);
      const markdown = this.generateMarkdown(draft);
      await fs.writeFile(mdPath, markdown, 'utf-8');
      result.mdPath = mdPath;
    }

    return result;
  }

  generateMarkdown(draft: IOnboardingDraft): string {
    const lines: string[] = [];

    // Header with disclaimer
    lines.push('# Packmind Onboarding Draft');
    lines.push('');
    lines.push(
      '> **GENERATED DRAFT** - This file was auto-generated by `packmind-onboard`.',
    );
    lines.push(
      '> - This file is **editable** - modify it before sending if needed',
    );
    lines.push(
      '> - You can **delete** this file anytime - nothing has been sent yet',
    );
    lines.push(
      '> - **Nothing is sent to Packmind** until you explicitly confirm',
    );
    lines.push('');
    lines.push('---');
    lines.push('');

    // Meta information
    lines.push('## Scan Information');
    lines.push('');
    lines.push(`- **Generated at:** ${draft.meta.generated_at}`);
    lines.push(`- **Repo fingerprint:** \`${draft.meta.repo_fingerprint}\``);
    lines.push(`- **Read-only scan:** ${draft.meta.read_only ? 'Yes' : 'No'}`);
    lines.push('');

    // Summary
    lines.push('## What We Detected');
    lines.push('');
    if (draft.summary.languages.length > 0) {
      lines.push(`**Languages:** ${draft.summary.languages.join(', ')}`);
    }
    if (draft.summary.frameworks.length > 0) {
      lines.push(`**Frameworks:** ${draft.summary.frameworks.join(', ')}`);
    }
    if (draft.summary.tools.length > 0) {
      lines.push(`**Tools:** ${draft.summary.tools.join(', ')}`);
    }
    if (draft.summary.structure_hints.length > 0) {
      lines.push(`**Structure:** ${draft.summary.structure_hints.join(', ')}`);
    }
    lines.push('');

    // Baseline items
    lines.push('## Baseline Items');
    lines.push('');
    lines.push(
      `Found **${draft.baseline_items.length}** items to include in your baseline:`,
    );
    lines.push('');

    for (const item of draft.baseline_items) {
      lines.push(`### ${item.label}`);
      lines.push('');
      lines.push(`- **Type:** ${item.type}`);
      lines.push(`- **Confidence:** ${item.confidence}`);
      lines.push(
        `- **Evidence:** ${item.evidence.map((e) => `\`${e}\``).join(', ')}`,
      );
      lines.push(`- **ID:** \`${item.id}\``);
      lines.push('');
    }

    // What will be sent
    lines.push('---');
    lines.push('');
    lines.push('## What Will Be Sent If You Approve');
    lines.push('');
    lines.push('When you confirm, the following will be sent to Packmind:');
    lines.push('');
    lines.push(`- **${draft.baseline_items.length}** baseline items`);
    lines.push('- Summary of detected technologies');
    lines.push('- Repo fingerprint (for tracking, not repo contents)');
    lines.push('');
    lines.push('**No source code or file contents will be sent.**');
    lines.push('');

    // How to edit/delete/regenerate
    lines.push('---');
    lines.push('');
    lines.push('## How to Proceed');
    lines.push('');
    lines.push('### Edit this draft');
    lines.push(
      'Modify this file or the companion `.json` file before confirming.',
    );
    lines.push('');
    lines.push('### Delete this draft');
    lines.push('Simply delete this file. Nothing will be sent to Packmind.');
    lines.push('');
    lines.push('### Regenerate');
    lines.push('Run `packmind-cli onboard` again to rescan and regenerate.');
    lines.push('');
    lines.push('### Send to Packmind');
    lines.push('Run `packmind-cli onboard --send` or follow the CLI prompts.');
    lines.push('');

    return lines.join('\n');
  }
}
