import React from 'react';
import { PMButton, PMText, PMVStack } from '@packmind/ui';

interface FalsePositivesSectionProps {
  onCodeExamplesClick: () => void;
}

export const FalsePositivesSection: React.FC<FalsePositivesSectionProps> = ({
  onCodeExamplesClick,
}) => {
  return (
    <PMVStack alignItems="flex-start" gap={2}>
      <PMText fontSize="sm" fontWeight="medium">
        Deal with false-positives
      </PMText>
      <PMText fontSize="sm" color="faded">
        Program is generated by AI and might miss (or wrongly detect)
        violations. Add Code examples illustrating these cases to generate a new
        program.
      </PMText>
      <PMButton size="sm" variant="outline" onClick={onCodeExamplesClick}>
        Code examples
      </PMButton>
    </PMVStack>
  );
};
