import React from 'react';
import { render, RenderResult } from '@testing-library/react';
import { UIProvider } from '@packmind/ui';
import userEvent from '@testing-library/user-event';
import { FalsePositivesSection } from './FalsePositivesSection';

describe('FalsePositivesSection', () => {
  let screen: RenderResult;
  let onCodeExamplesClick: jest.Mock;

  beforeEach(() => {
    onCodeExamplesClick = jest.fn();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  function renderWithContext() {
    return render(
      <UIProvider>
        <FalsePositivesSection onCodeExamplesClick={onCodeExamplesClick} />
      </UIProvider>,
    );
  }

  describe('when rendered', () => {
    beforeEach(() => {
      screen = renderWithContext();
    });

    it('shows "Deal with false-positives" heading', () => {
      expect(
        screen.getByText(/Deal with false-positives/i),
      ).toBeInTheDocument();
    });

    it('shows description about program being generated by AI', () => {
      expect(
        screen.getByText(/Program is generated by AI/i),
      ).toBeInTheDocument();
    });

    it('shows "Code examples" button', () => {
      expect(screen.getByText('Code examples')).toBeInTheDocument();
    });

    it('calls onCodeExamplesClick when "Code examples" button is clicked', async () => {
      const user = userEvent.setup();
      const button = screen.getByText('Code examples');

      await user.click(button);

      expect(onCodeExamplesClick).toHaveBeenCalledTimes(1);
    });
  });
});
