import React from 'react';
import { PMLink, PMText, PMVStack } from '@packmind/ui';

interface InformationSectionProps {
  version?: number;
  generatedBy?: string;
  createdAt?: Date | string;
  onGenerationDetailsClick: () => void;
}

const formatDate = (date: Date | string): string => {
  const dateObj = typeof date === 'string' ? new Date(date) : date;
  return dateObj.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });
};

export const InformationSection: React.FC<InformationSectionProps> = ({
  version,
  generatedBy,
  createdAt,
  onGenerationDetailsClick,
}) => {
  return (
    <PMVStack alignItems="flex-start" gap={2}>
      <PMText fontSize="sm" fontWeight="medium">
        Information
      </PMText>
      {version && (
        <PMText fontSize="sm" color="faded">
          Version: {version}
        </PMText>
      )}
      {generatedBy && createdAt && (
        <PMText fontSize="sm" color="faded">
          Generated by {generatedBy}, on {formatDate(createdAt)}
        </PMText>
      )}
      <PMLink fontSize="sm" onClick={onGenerationDetailsClick} cursor="pointer">
        Generation details
      </PMLink>
    </PMVStack>
  );
};
