import React from 'react';
import { render, RenderResult } from '@testing-library/react';
import { UIProvider } from '@packmind/ui';
import userEvent from '@testing-library/user-event';
import { InformationSection } from './InformationSection';

describe('InformationSection', () => {
  let screen: RenderResult;
  let onGenerationDetailsClick: jest.Mock;

  beforeEach(() => {
    onGenerationDetailsClick = jest.fn();
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  function renderWithContext(
    version?: number,
    generatedBy?: string,
    createdAt?: Date,
  ) {
    return render(
      <UIProvider>
        <InformationSection
          version={version}
          generatedBy={generatedBy}
          createdAt={createdAt}
          onGenerationDetailsClick={onGenerationDetailsClick}
        />
      </UIProvider>,
    );
  }

  describe('when version is provided', () => {
    beforeEach(() => {
      screen = renderWithContext(2);
    });

    it('shows version number', () => {
      expect(screen.getByText(/Version: 2/i)).toBeInTheDocument();
    });
  });

  describe('when generatedBy and createdAt are provided', () => {
    beforeEach(() => {
      const date = new Date('2024-10-19');
      screen = renderWithContext(2, 'John Doe', date);
    });

    it('shows generated by information', () => {
      expect(screen.getByText(/Generated by John Doe/i)).toBeInTheDocument();
    });

    it('shows generation date', () => {
      // Date format may vary, so check for the date pattern
      expect(screen.getByText(/Generated by John Doe/i)).toBeInTheDocument();
      expect(screen.getByText(/, on/i)).toBeInTheDocument();
    });
  });

  describe('when generation details link is clicked', () => {
    beforeEach(() => {
      screen = renderWithContext(2, 'John Doe', new Date('2024-10-19'));
    });

    it('calls onGenerationDetailsClick', async () => {
      const user = userEvent.setup();
      const link = screen.getByText('Generation details');

      await user.click(link);

      expect(onGenerationDetailsClick).toHaveBeenCalledTimes(1);
    });
  });
});
