#!/usr/bin/env bun

/**
 * Embeds WASM files as base64-encoded strings into a TypeScript module
 * This allows the CLI executable to extract WASM files at runtime
 */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { resolve, join } from 'path';

const WASM_SOURCE_DIR = resolve(__dirname, '../../../packages/linter-ast/res');
const OUTPUT_FILE = resolve(__dirname, '../src/embedded-wasm.ts');
const logger = console;

logger.log('🔧 Embedding WASM files...');

const wasmFiles = readdirSync(WASM_SOURCE_DIR).filter((f) =>
  f.endsWith('.wasm'),
);

const embeddedWasmData: Record<string, string> = {};

for (const wasmFile of wasmFiles) {
  const wasmPath = join(WASM_SOURCE_DIR, wasmFile);
  const wasmBuffer = readFileSync(wasmPath);
  const base64Data = wasmBuffer.toString('base64');
  embeddedWasmData[wasmFile] = base64Data;
  logger.log(
    `  ✓ Embedded ${wasmFile} (${(wasmBuffer.length / 1024).toFixed(2)} KB)`,
  );
}

const outputContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by apps/cli/scripts/embed-wasm-files.ts

export const EMBEDDED_WASM_FILES: Record<string, string> = ${JSON.stringify(embeddedWasmData, null, 2)};
`;

writeFileSync(OUTPUT_FILE, outputContent);

logger.log(`\n✅ Embedded ${wasmFiles.length} WASM files to ${OUTPUT_FILE}`);
logger.log(
  `📦 Total size: ${(JSON.stringify(embeddedWasmData).length / 1024 / 1024).toFixed(2)} MB`,
);
