#!/usr/bin/env node

/**
 * Generates a TypeScript module containing the CLI version from package.json
 * This allows the CLI to access its version at runtime without file system access
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { readFileSync, writeFileSync } = require('fs');
const { resolve } = require('path');

const PACKAGE_JSON_PATH = resolve(__dirname, '../package.json');
const OUTPUT_FILE = resolve(__dirname, '../src/generated-version.ts');

console.log('🔧 Generating version module...');

const packageJson = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf-8'));
const version = packageJson.version;

if (!version) {
  console.error('❌ Error: No version found in package.json');
  process.exit(1);
}

const outputContent = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by apps/cli/scripts/generate-version.ts

export const CLI_VERSION = '${version}';
`;

writeFileSync(OUTPUT_FILE, outputContent);

console.log(`✅ Generated version module: ${version}`);
console.log(`📄 Output: ${OUTPUT_FILE}`);
