import * as path from 'path';

/**
 * Self-contained tsconfig consumed by ArchUnitTS. Generated by
 * `scripts/build-arch-tsconfig.mjs` (run by the `arch` Nx target) from the
 * edition-aware effective config, so `@packmind/*` aliases resolve and the
 * monorepo sources are discovered. Paths in violations are relative to repo root
 * (e.g. `packages/recipes/src/...`), which is what the rule globs below match.
 */
export const ARCH_TSCONFIG = path.resolve(
  __dirname,
  '../../../tsconfig.arch.json',
);

/**
 * Domain (hexagon) packages under `packages/`. These follow the ports & adapters
 * layout (application / domain / infra) and may only talk to each other through
 * `@packmind/types` ports — never by importing each other's source directly.
 *
 * Maintained explicitly (not auto-discovered) on purpose: a domain package that
 * is *missing* its expected hexagon layers is itself an architecture problem we
 * want surfaced, not silently skipped. Add every new domain package here.
 *
 * Infrastructure/shared packages (types, logger, node-utils, test-utils,
 * migrations, ui, frontend, assets, editions, linter-*) are intentionally
 * excluded: they are not domains and have different layering.
 */
export const DOMAIN_PACKAGES = [
  'accounts',
  'spaces',
  'standards',
  'recipes',
  'skills',
  'git',
  'deployments',
  'coding-agent',
  'llm',
] as const;

/**
 * Glob fragments tolerant of the small folder-naming inconsistencies across
 * packages (e.g. `useCases` vs `usecases`, `adapter` vs `adapters`). Matched as
 * full repo-relative paths via `inPath`.
 */
export const LAYER_GLOBS = {
  // Use case classes — `useCases` (most) and `usecases` (spaces).
  useCases: 'packages/*/src/application/use[cC]ases/**',
  // Domain adapters — `adapter` (most) and `adapters` (spaces).
  adapters: 'packages/*/src/application/adapter*/**',
  // Application services.
  services: 'packages/*/src/application/services/**',
  // The whole application layer (use cases + adapters + services + jobs).
  application: 'packages/*/src/application/**',
  // Domain layer: entities, repository interfaces (ports), domain services.
  domain: 'packages/*/src/domain/**',
  // Infrastructure layer (repository implementations, TypeORM schemas, jobs).
  infra: 'packages/*/src/infra/**',
  // Concrete repository implementations only (NOT schemas/entities).
  repositories: 'packages/*/src/infra/repositories/**',
  // TypeORM EntitySchema definitions (pure ORM mapping).
  schemas: 'packages/*/src/infra/schemas/**',
  // The shared contract package (ports, contracts, events, entity types).
  types: 'packages/types/src/**',
  // The whole NestJS API app (controllers, modules, providers).
  apiAll: 'apps/api/src/**/*.ts',
} as const;

/**
 * Matches the source of ANY domain package. Used by reverse-dependency rules
 * (shared/base packages and the contract package must not depend on domains).
 * Built the same way as the per-domain target in `cross-domain.arch.spec.ts`.
 */
export const DOMAIN_SRC_REGEX = new RegExp(
  `packages/(${DOMAIN_PACKAGES.join('|')})/src/`,
);

/**
 * Matches the source of the shared/base packages that domains build on top of.
 * These must never depend back on a domain (would create a cycle / inversion).
 */
export const SHARED_BASE_REGEX = /packages\/(node-utils|logger)\/src\//;
