import * as fs from 'fs';
import * as path from 'path';
import {
  describeWithUserSignedUp,
  runCli,
  updateFile,
  setupGitRepo,
  IPackmindGateway,
} from './helpers';
import {
  ChangeProposalType,
  GetTargetsByOrganizationCommand,
  ListChangeProposalsByArtefactResponse,
  Package,
  Recipe,
  SpaceId,
  TargetWithRepository,
} from '@packmind/types';

describeWithUserSignedUp('diff remove <path> command', (getContext) => {
  let gateway: IPackmindGateway;
  let apiKey: string;
  let testDir: string;
  let spaceId: SpaceId;
  let command: Recipe;
  let pkg: Package;

  beforeEach(async () => {
    const context = await getContext();
    await setupGitRepo(context.testDir);

    apiKey = context.apiKey;
    testDir = context.testDir;
    spaceId = context.spaceId;
    gateway = context.gateway;

    command = await gateway.commands.create({
      name: 'My command',
      content: '# My Command\n\nThis is my command content.',
      spaceId,
    });

    const createPackageResponse = await gateway.packages.create({
      name: 'My package',
      description: 'Test package for diff command',
      recipeIds: [command.id],
      standardIds: [],
      spaceId,
    });
    pkg = createPackageResponse.package;

    // Install the package locally
    const installResult = await runCli(`install ${pkg.slug}`, {
      apiKey,
      cwd: testDir,
    });

    if (installResult.returnCode !== 0) {
      throw new Error(
        `Failed to install package: ${installResult.stderr || installResult.stdout}`,
      );
    }
  });

  describe('when the path does not exist', () => {
    let returnCode: number;
    let stderr: string;

    beforeEach(async () => {
      const result = await runCli(
        'diff remove .packmind/commands/nonexistent.md',
        {
          apiKey,
          cwd: testDir,
        },
      );

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('File or directory does not exist');
    });
  });

  describe('when the path point to a file which is not an artefact', () => {
    let returnCode: number;
    let stderr: string;

    beforeEach(async () => {
      updateFile('README.md', '# About my project', testDir);

      const result = await runCli('diff remove README.md', {
        apiKey,
        cwd: testDir,
      });

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('Unsupported file path');
    });
  });

  describe('when the path point to a file which was not generated by packmind', () => {
    let returnCode: number;
    let stderr: string;

    const nonpackmindCommandPath = '.packmind/commands/my-custom-command.md';

    beforeEach(async () => {
      updateFile(nonpackmindCommandPath, '# Whatever data here', testDir);

      const result = await runCli(`diff remove ${nonpackmindCommandPath}`, {
        apiKey,
        cwd: testDir,
      });

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('This command does not come from Packmind');
    });
  });

  describe('when the path point to a file generated by packmind', () => {
    let returnCode: number;
    let stdout: string;
    let stderr: string;

    beforeEach(async () => {
      const result = await runCli(
        `diff remove .packmind/commands/${command.slug}.md -m "Remove command from project"`,
        {
          apiKey,
          cwd: testDir,
        },
      );

      returnCode = result.returnCode;
      stdout = result.stdout;
      stderr = result.stderr;
    });

    it('succeeds', () => {
      if (returnCode !== 0) {
        console.log('stderr:', stderr);
        console.log('stdout:', stdout);
      }
      expect(returnCode).toEqual(0);
    });

    it('notifies the user that the change proposal was submitted', () => {
      expect(stdout).toContain('Change proposal for removal submitted');
    });

    it('deletes the file', () => {
      const filePath = path.join(
        testDir,
        `.packmind/commands/${command.slug}.md`,
      );
      expect(fs.existsSync(filePath)).toBe(false);
    });

    describe('when verifying change proposal creation', () => {
      let rootTarget: TargetWithRepository | undefined;
      let changeProposalsByRecipeResponse: ListChangeProposalsByArtefactResponse;

      beforeEach(async () => {
        // Get targets to find the root target created by install
        const targetsCommand: GetTargetsByOrganizationCommand = {
          userId: '',
          organizationId: '',
        };
        const targets =
          await gateway.deployments.getTargetsByOrganization(targetsCommand);
        rootTarget = targets.find((t) => t.path === '/');

        if (rootTarget) {
          changeProposalsByRecipeResponse =
            await gateway.deployments.listChangeProposalsByRecipe({
              spaceId,
              artefactId: command.id,
            });
        }
      });

      it('creates a root target from install', () => {
        expect(rootTarget).toBeDefined();
      });

      it('creates a change proposal with correct type and payload', () => {
        expect(changeProposalsByRecipeResponse).toEqual({
          changeProposals: [
            expect.objectContaining({
              type: ChangeProposalType.removeCommand,
              artefactId: command.id,
              payload: {
                targetId: rootTarget?.id,
                packageIds: [pkg.id],
              },
            }),
          ],
        });
      });
    });
  });
});
