import {
  describeWithUserSignedUp,
  runCli,
  updateFile,
  setupGitRepo,
  IPackmindGateway,
} from './helpers';
import { SpaceId } from '@packmind/types';

describeWithUserSignedUp('diff remove <path> command', (getContext) => {
  let gateway: IPackmindGateway;
  let apiKey: string;
  let testDir: string;
  let spaceId: SpaceId;
  let commandSlug: string;

  beforeEach(async () => {
    const context = await getContext();
    await setupGitRepo(context.testDir);

    apiKey = context.apiKey;
    testDir = context.testDir;
    spaceId = context.spaceId;
    gateway = context.gateway;

    const command = await gateway.commands.create({
      name: 'My command',
      content: '# My Command\n\nThis is my command content.',
      spaceId,
    });
    commandSlug = command.slug;

    const createPackageResponse = await gateway.packages.create({
      name: 'My package',
      description: 'Test package for diff command',
      recipeIds: [command.id],
      standardIds: [],
      spaceId,
    });

    // Install the package locally
    const installResult = await runCli(
      `install ${createPackageResponse.package.slug}`,
      {
        apiKey,
        cwd: testDir,
      },
    );

    if (installResult.returnCode !== 0) {
      throw new Error(
        `Failed to install package: ${installResult.stderr || installResult.stdout}`,
      );
    }
  });

  describe('when the path does not exist', () => {
    let returnCode: number;
    let stderr: string;

    beforeEach(async () => {
      const result = await runCli(
        'diff remove .packmind/commands/nonexistent.md',
        {
          apiKey,
          cwd: testDir,
        },
      );

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('File or directory does not exist');
    });
  });

  describe('when the path point to a file which is not an artefact', () => {
    let returnCode: number;
    let stderr: string;

    beforeEach(async () => {
      updateFile('README.md', '# About my project', testDir);

      const result = await runCli('diff remove README.md', {
        apiKey,
        cwd: testDir,
      });

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('Unsupported file path');
    });
  });

  describe('when the path point to a file which was not generated by packmind', () => {
    let returnCode: number;
    let stderr: string;

    const nonpackmindCommandPath = '.packmind/commands/my-custom-command.md';

    beforeEach(async () => {
      updateFile(nonpackmindCommandPath, '# Whatever data here', testDir);

      const result = await runCli(`diff remove ${nonpackmindCommandPath}`, {
        apiKey,
        cwd: testDir,
      });

      returnCode = result.returnCode;
      stderr = result.stderr;
    });

    it('fails', () => {
      expect(returnCode).toEqual(1);
    });

    it('notifies the user that this path is invalid', () => {
      expect(stderr).toContain('This command does not come from Packmind');
    });
  });

  describe('when the path point to a file generated by packmind', () => {
    let returnCode: number;
    let stdout: string;

    beforeEach(async () => {
      const result = await runCli(
        `diff remove .packmind/commands/${commandSlug}.md`,
        {
          apiKey,
          cwd: testDir,
        },
      );

      returnCode = result.returnCode;
      stdout = result.stdout;
    });

    it('succeeds', () => {
      expect(returnCode).toEqual(0);
    });

    it('notifies the user that the artifact can be removed', () => {
      expect(stdout).toContain('This artefact can be removed');
    });
  });
});
