import { ProgrammingLanguage } from '../languages';
import { Rule } from '../standards';
import { RuleExample } from '../standards';

// The input to a detection-program generation, gathered into one type rather
// than passed as separate arguments.
export type DetectionProgramRuleInput = {
  rule: Rule;
  ruleExamples: RuleExample[]; // We assume that the ruleExamples are filtered based on the programmingLanguage, to avoid filtering operations everytime we need to compute examples
  language: ProgrammingLanguage;
  heuristics?: string[]; // Detection heuristics generated by AI to guide the detection program generation
};
