import { SpaceListItem } from './types';

export const MOCK_SPACES: SpaceListItem[] = [
  {
    id: 'space-1',
    name: 'Global',
    colorToken: 'purple',
    isOrgWide: true,
    admins: [
      { id: 'u-ct', displayName: 'Charlie Thompson' },
      { id: 'u-sd', displayName: 'Sarah Davis' },
      { id: 'u-mc', displayName: 'Mike Chen' },
      { id: 'u-jr', displayName: 'Joan Racenet' },
      { id: 'u-vp', displayName: 'Vincent Pretre' },
    ],
    membersCount: 46,
    artifactsCount: 120,
    createdAt: '2025-01-12',
  },
  {
    id: 'space-2',
    name: 'Frontend',
    colorToken: 'orange',
    isOrgWide: false,
    admins: [
      { id: 'u-ct', displayName: 'Charlie Thompson' },
      { id: 'u-sd', displayName: 'Sarah Davis' },
      { id: 'u-jr', displayName: 'Joan Racenet' },
    ],
    membersCount: 14,
    artifactsCount: 42,
    createdAt: '2025-02-03',
  },
  {
    id: 'space-3',
    name: 'Backend',
    colorToken: 'green',
    isOrgWide: false,
    admins: [
      { id: 'u-sd', displayName: 'Sarah Davis' },
      { id: 'u-ql', displayName: 'Quentin Lebourles' },
      { id: 'u-vp', displayName: 'Vincent Pretre' },
    ],
    membersCount: 18,
    artifactsCount: 58,
    createdAt: '2025-02-03',
  },
  {
    id: 'space-4',
    name: 'Mobile',
    colorToken: 'red',
    isOrgWide: false,
    admins: [
      { id: 'u-mc', displayName: 'Mike Chen' },
      { id: 'u-tb', displayName: 'Tina Brown' },
    ],
    membersCount: 9,
    artifactsCount: 24,
    createdAt: '2025-02-18',
  },
  {
    id: 'space-5',
    name: 'Data',
    colorToken: 'blue',
    isOrgWide: false,
    admins: [
      { id: 'u-ql', displayName: 'Quentin Lebourles' },
      { id: 'u-vp', displayName: 'Vincent Pretre' },
    ],
    membersCount: 11,
    artifactsCount: 33,
    createdAt: '2025-02-22',
  },
  {
    id: 'space-6',
    name: 'Platform',
    colorToken: 'purple',
    isOrgWide: false,
    admins: [{ id: 'u-vp', displayName: 'vincent.pretre' }],
    membersCount: 7,
    artifactsCount: 19,
    createdAt: '2025-03-04',
  },
  {
    id: 'space-7',
    name: 'Design',
    colorToken: 'red',
    isOrgWide: false,
    admins: [
      { id: 'u-jr', displayName: 'Joan Racenet' },
      { id: 'u-ct', displayName: 'Charlie Thompson' },
    ],
    membersCount: 6,
    artifactsCount: 14,
    createdAt: '2025-03-15',
  },
  {
    id: 'space-8',
    name: 'Growth',
    colorToken: 'beige',
    isOrgWide: false,
    admins: [{ id: 'u-ct', displayName: 'cedric.teyton' }],
    membersCount: 5,
    artifactsCount: 9,
    createdAt: '2025-03-28',
  },
  ...Array.from({ length: 24 }, (_, i): SpaceListItem => {
    const palettes: SpaceListItem['colorToken'][] = [
      'beige',
      'blue',
      'orange',
      'red',
      'green',
      'purple',
    ];
    return {
      id: `space-filler-${i + 9}`,
      name: `Squad ${i + 9}`,
      colorToken: palettes[i % palettes.length],
      isOrgWide: false,
      admins: [
        {
          id: `u-filler-${i}-a`,
          displayName: `Alex Number${i + 9}`,
        },
      ],
      membersCount: 3 + (i % 9),
      artifactsCount: 5 + (i % 17),
      createdAt: `2025-04-${String((i % 28) + 1).padStart(2, '0')}`,
    };
  }),
];
