export enum ChangeProposalType {
  updateCommandName = 'updateCommandName',
  updateCommandDescription = 'updateCommandDescription',
  updateStandardName = 'updateStandardName',
  updateStandardDescription = 'updateStandardDescription',
  updateStandardScope = 'updateStandardScope',
  addRule = 'addRule',
  updateRule = 'updateRule',
  deleteRule = 'deleteRule',
  updateSkillName = 'updateSkillName',
  updateSkillDescription = 'updateSkillDescription',
  updateSkillPrompt = 'updateSkillPrompt',
  updateSkillMetadata = 'updateSkillMetadata',
  updateSkillLicense = 'updateSkillLicense',
  updateSkillCompatibility = 'updateSkillCompatibility',
  updateSkillAllowedTools = 'updateSkillAllowedTools',
  addSkillFile = 'addSkillFile',
  updateSkillFileContent = 'updateSkillFileContent',
  updateSkillFilePermissions = 'updateSkillFilePermissions',
  deleteSkillFile = 'deleteSkillFile',
}
