import { ChangeProposalType } from './ChangeProposalType';

export const CHANGE_PROPOSAL_TYPE_LABELS: Record<ChangeProposalType, string> = {
  [ChangeProposalType.updateCommandName]: 'Name',
  [ChangeProposalType.updateCommandDescription]: 'Instructions updated',
  [ChangeProposalType.updateStandardName]: 'Name',
  [ChangeProposalType.updateStandardDescription]: 'Description',
  [ChangeProposalType.updateStandardScope]: 'Scope',
  [ChangeProposalType.addRule]: 'Rule (add)',
  [ChangeProposalType.updateRule]: 'Rule (update)',
  [ChangeProposalType.deleteRule]: 'Rule (delete)',
  [ChangeProposalType.updateSkillName]: 'Name',
  [ChangeProposalType.updateSkillDescription]: 'Description',
  [ChangeProposalType.updateSkillPrompt]: 'Prompt',
  [ChangeProposalType.updateSkillMetadata]: 'Metadata',
  [ChangeProposalType.updateSkillLicense]: 'License',
  [ChangeProposalType.updateSkillCompatibility]: 'Compatibility',
  [ChangeProposalType.updateSkillAllowedTools]: 'Allowed Tools',
  [ChangeProposalType.addSkillFile]: 'File (add)',
  [ChangeProposalType.updateSkillFileContent]: 'File content',
  [ChangeProposalType.updateSkillFilePermissions]: 'File permissions',
  [ChangeProposalType.deleteSkillFile]: 'File (delete)',
  [ChangeProposalType.newStandard]: 'New standard',
  [ChangeProposalType.newCommand]: 'New command',
  [ChangeProposalType.newSkill]: 'New skill',
};
