export enum ChangeProposalViolation {
  // Standard size limits.
  STANDARD_NAME_TOO_LONG = 'STANDARD_NAME_TOO_LONG',
  TOO_MANY_RULES = 'TOO_MANY_RULES',
  RULE_CONTENT_TOO_LONG = 'RULE_CONTENT_TOO_LONG',

  // Structural and lookup failures.
  PAYLOAD_MISMATCH = 'PAYLOAD_MISMATCH',
  UNSUPPORTED_TYPE = 'UNSUPPORTED_TYPE',
  SKILL_FILE_NOT_FOUND = 'SKILL_FILE_NOT_FOUND',
  SKILL_VERSION_NOT_FOUND = 'SKILL_VERSION_NOT_FOUND',
}
