// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by apps/cli/scripts/embed-wasm-files.ts
//
// This file is populated during executable build (bun-build.ts)
// For npm package builds, this remains empty (WASM files are in assets)

export const EMBEDDED_WASM_FILES: Record<string, string> = {};
